name: corewallet_desktop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gradient_borders: ^1.0.0
  flutter_glow: ^0.2.0
  flutter_svg: ^2.0.4
  responsive_framework: ^0.2.0
  cached_network_image: ^3.2.3
  socket_io_client: ^2.0.1


  # generate qr scanner
  qr_flutter: ^4.1.0

  clipboard: ^0.1.3

  path: ^1.8.2
  provider: ^6.0.5

  #charts plugin
  syncfusion_flutter_charts: ^21.1.35
  fl_chart: ^0.61.0
  country_list_pick: ^1.0.1+6


  dotted_border: ^2.0.0+3
  flutter_switch: ^0.3.2
  intl: ^0.18.0
  hovering: ^1.0.4

  web3dart: ^2.6.1


  # window and macos screen size manage
  window_manager: ^0.3.1

#  expansion_tile_card: ^2.0.0
  currency_picker: ^2.0.16
  country_picker: ^2.0.20
  number_paginator: ^0.2.3
  http: ^0.13.5
  country_currency_pickers: ^2.0.0
  change_app_package_name: ^1.1.0

  #local data base
  path_provider: ^2.0.14
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2

  #toast and loader
  fluttertoast: ^8.2.1
  flutter_styled_toast: ^2.1.3
  flutter_spinkit: ^5.1.0
  flutter_custom_clippers: ^2.1.0
  shared_preferences: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2


  #encrypt
  encrypt: ^5.0.1

  # platform device id
  platform_device_id: ^1.0.1
  flutter_slidable: ^2.0.0
  declarative_refresh_indicator: ^0.1.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.10
  rename: ^2.1.1

dev_dependencies:
  flutter_test:

    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^1.0.0
  macos:
    generate: true
    image_path: "assets/colorlogoonly.svg"
  windows:
    generate: true
    image_path: "assets/colorlogoonly.svg"
    icon_size: 44


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/wallet/
    - assets/icons/drawericon/
    - assets/icons/Market/
    - assets/icons/Exchange/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Sf-Regular
      fonts:
        - asset: assets/font/FontsFree-Net-SFProText-Regular.ttf
    - family: Sf-SemiBold
      fonts:
        - asset: assets/font/SF-Pro-Text-Semibold.otf

    - family: Sf-Medium
      fonts:
        - asset: assets/font/SF-Pro-Text-Medium.otf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages